site_name: StarRail NPR Shader Docs
site_description: "Fan-made shaders for Unity URP attempting to replicate the shading of Honkai: Star Rail."
repo_name: stalomeow/StarRailNPRShader
repo_url: https://github.com/stalomeow/StarRailNPRShader
edit_uri: https://github.com/stalomeow/StarRailNPRShaderDocs/blob/main/docs/ # do not use "edit/main/docs/"

theme:
  name: material
  language: en
  favicon: assets/favicon.ico
  logo: assets/logo-en.png

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

  palette:
    - scheme: slate
      primary: black

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit

    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.indexes
    # - navigation.tracking
    - navigation.footer
    - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - assets/style.css

extra_javascript:
  # - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-chtml.js # 别加 mml！它会导致表格横向溢出！
  - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.6/tex-chtml.js

markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
      line_spans: __span # When this option is set, each line of a code block is wrapped in a span, which is essential for features like line highlighting to work correctly
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      # https://python-markdown.github.io/extensions/toc/
      permalink: true
      separator: "-"
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

hooks:
  - scripts/fancybox.py

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  links:
    anchors: warn
    unrecognized_links: warn

plugins:
  - search:
      lang:
        - zh
        - en
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          site_name: StarRail NPR Shader 文档
          theme:
            logo: assets/logo-zh.png
          nav_translations:
            Home: 首页
            Installation: 安装
            Character: 角色
            Asset and Material: 资产和材质
            Rendering Controller: 渲染控制器
            MMD Model: MMD 模型
            Advanced: 高级
            Material Automation: 自动设置材质
            A Rough Flow Chart of This Pipeline: 该管线的大致流程图

nav:
  - Home: index.md
  - Installation: installation.md
  - Character:
    - Asset and Material: character/asset-and-material.md
    - Rendering Controller: character/rendering-controller.md
    - MMD Model: character/mmd-model.md
  - Advanced:
    - Material Automation: advanced/material-automation.md
    - A Rough Flow Chart of This Pipeline: advanced/a-rough-flow-chart-of-this-pipeline.md
