site_name: StarRail NPR Shader Docs
site_url: https://srshader.stalomeow.com/
site_description: "Fan-made shaders for Unity URP attempting to replicate the shading of Honkai: Star Rail."
repo_name: stalomeow/StarRailNPRShader
repo_url: https://github.com/stalomeow/StarRailNPRShader
edit_uri: https://github.com/stalomeow/StarRailNPRShaderDocs/blob/main/docs/ # do not use "edit/main/docs/"
copyright: Copyright &copy; 2023 - 2024 stalomeow

theme:
  name: material
  language: en
  favicon: assets/favicon.ico
  logo: assets/logo-en.png

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

  palette:
    - scheme: slate
      primary: black

  features:
    - announce.dismiss

    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - content.action.edit

    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.indexes
    # - navigation.tracking
    - navigation.footer
    - navigation.sections

    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share

extra:
  generator: false
  version:
    provider: mike
    alias: true
  social:
    - name: Sponsor
      icon: fontawesome/solid/heart
      link: https://stalomeow.com/#coffee
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/stalomeow/StarRailNPRShader

extra_css:
  - assets/stylesheets/custom.css

# extra_javascript:
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.6/tex-chtml.js

markdown_extensions:
  - abbr
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      # auto_title: true
      linenums: true
      anchor_linenums: true
      use_pygments: true
      line_spans: __span # When this option is set, each line of a code block is wrapped in a span, which is essential for features like line highlighting to work correctly
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      # https://python-markdown.github.io/extensions/toc/
      permalink: true
      separator: "-"
      # 生成可读的 unicode slug
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

hooks:
  - scripts/fancybox.py

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  links:
    anchors: warn
    unrecognized_links: warn

plugins:
  - search:
      lang:
        - zh
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      # css minify 和 i18n 一起用有 bug
      # css_files:
      #   - assets/stylesheets/custom.css
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: zh
          name: 简体中文
          build: true
          site_name: StarRail NPR Shader 文档
          site_description: 基于 Unity URP 的仿星穹铁道渲染 Shader
          theme:
            logo: assets/logo-zh.png
          nav_translations:
            Home: 首页
            Installation: 安装
            Character: 角色
            Asset and Material: 资产和材质
            Rendering Controller: 渲染控制器
            Generate Material Automatically: 自动生成材质
            Advanced: 高级
            A Flowchart of Rendering: 渲染流程图
            Sample Character Shadow: 采样角色阴影

nav:
  - Home: index.md
  - Installation: installation.md
  - Character:
    - Asset and Material: character/asset-and-material.md
    - Rendering Controller: character/rendering-controller.md
    - Generate Material Automatically: character/generate-material-automatically.md
  - Advanced:
    - A Flowchart of Rendering: advanced/a-flowchart-of-rendering.md
    - Sample Character Shadow: advanced/sample-character-shadow.md
